export const BOT_REGISTER_SUCCESS = 'BOT_REGISTER_SUCCESS'
export const LOAD_BOTS_SUCCESS = 'LOAD_BOTS'

export const BOT_UPDATE_MESSAGE ='BOT_UPDATE_MESSAGE'

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const LOAD_MESSAGE_SUCCESS = 'LOAD_MESSAGE_SUCCESS'