export const BOT_REGISTER_SUCCESS = 'BOT_REGISTER_SUCCESS'
export const LOAD_BOTS_SUCCESS = 'LOAD_BOTS'

export const BOT_UPDATE_MESSAGE = 'BOT_UPDATE_MESSAGE'
export const BOT_REQUEST_MESSAGE = 'BOT_REQUEST_MESSAGE'

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const LOAD_MESSAGE_SUCCESS = 'LOAD_MESSAGE_SUCCESS'
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS'
// channel
export const CHANGE_TITLE_CHANNEL_SUCCESS = 'CHANGE_TITLE_CHANNEL_SUCCESS'

// user
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_REQUEST = 'LOAD_USERS_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'

// register
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
// auth
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILD = 'USER_LOGIN_FAILD'